blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/FreeSideNomad/tide/wiki
    about: View project documentation and domain model
  - name: 💬 Discussions
    url: https://github.com/FreeSideNomad/tide/discussions
    about: Ask questions and discuss ideas with the community